spring:
  application.name: YnabImport
  cloud.loadbalancer.ribbon.enabled: false
  profiles.include: private
  output.ansi.enabled: ALWAYS

management.endpoints.web.exposure.include: '*'

feign:
  httpclient.enabled: true
  client.config.default.loggerLevel: basic

logging.level:
  com.rubenjg.ynab.client: DEBUG

ynab:
  url: https://api.youneedabudget.com/v1

